default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('POSTGRES_USERNAME') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: rweather_development

test:
  <<: *default
  database: rweather_test

production:
  <<: *default
  database: rweather_production
